apiVersion: v1
kind: Service
metadata:
  name: media-mongodb-service
spec:
  selector:
    app: media-mongodb
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-mongodb-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-mongodb-deployment
spec:
  selector:
    matchLabels:
      app: media-mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: media-mongodb
    spec:
      containers:
        - image: mongo:3.6.15-xenial
          name: mongodb
          ports:
            - containerPort: 27017
      volumes:
        - name: media-persistent-storage
          persistentVolumeClaim:
            claimName: media-mongodb-pv-claim
