apiVersion: v1
kind: Service
metadata:
  name: postgresdb-node-service
spec:
  selector:
    app: postgresdb-webservice
  ports:
    - port: 3000
      targetPort: 3000
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
spec:
  selector:
    matchLabels:
      app: postgresdb-webservice
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgresdb-webservice
    spec:
      containers:
        - image: gold96tendy/leaseit_user-service:0.0.1
          name: node-postgres-alpine
          ports:
            - containerPort: 3000
          env:
            - name: DB_POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: postgres_db_url



