apiVersion: v1
kind: Namespace
metadata:
  name: user-db
---
apiVersion: v1
kind: Service
metadata:
  name: media-postgres-service
  namespace: user-db
spec:
  selector:
    app: user-postgresdb
  ports:
    - port: 35432
      targetPort: 3542
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-postgres-pv-claim
  namespace: user-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-postgres-deployment
  namespace: user-db
spec:
  selector:
    matchLabels:
      app: user-postgresdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: user-postgresdb
    spec:
      containers:
        - image: postgres:alpine
          name: postgresdb
          env:
            - name: DB_POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: postgres_db_url
          ports:
            - containerPort: 27017
      volumes:
        - name: user-persistent-storage
          persistentVolumeClaim:
            claimName: user-postgres-pv-claim


