apiVersion: v1
kind: PersistentVolume
metadata:
  name: user-mongo-pv
  namespace: media-db
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/media-mongodb"