apiVersion: v1
kind: PersistentVolume
metadata:
  name: user-postgres-pv
  namespace: user-db
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"