---
apiVersion: v1
kind: Service
metadata:
  name: user-postgres-service
spec:
  selector:
    app: user-postgresdb
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-postgres-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-postgres-alpine
spec:
  selector:
    matchLabels:
      app: user-postgresdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: user-postgresdb
    spec:
      containers:
        - image: postgres:alpine
          name: postgresdb
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: postgres_user
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: postgres_db
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: postgres_password
      volumes:
        - name: user-persistent-storage
          persistentVolumeClaim:
            claimName: user-postgres-pv-claim


