apiVersion: v1
kind: Namespace
metadata:
  name: mongodb-node
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-node-service
  namespace: mongodb-node
spec:
  selector:
    app: mongodb-node-service
  ports:
    - port: 4000
      targetPort: 4000
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-mongodb-querier
  namespace: mongodb-node
spec:
  selector:
    matchLabels:
      app: mongdb-webservice
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongdb-webservice
    spec:
      containers:
        - image: gold96tendy/leaseit:mongo-service_alpine
          name: node-mongo-alpine
          ports:
            - containerPort: 4000
          env:
            - name: MONGO_DB_URL
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: mongo_db_url

