version: "3"
services:
  #mongo service need to fix names
  mongo-service:
    build: ./mongodb_service
    container_name: web-mongodb-service
    ports:
      - 4000:4000
    depends_on:
      - mongodb
    environment: 
      MONGO_DB_URL: mongodb://mongodb:27017
  mongodb:
    image: mongo:3.6.15-xenial
    container_name: media-data-store
    expose:
      - "27017"
    volumes:
      - ./mongodb_volume:/var/lib/mongodb/data
  postgres-service:
    build: ./postgres_service
    container_name: login-service-node
    ports:
      - "3000:3000"
    environment:
       - DB_POSTGRES_URL=postgres://user:1234@postgresdb:5432/customerdirectory
    depends_on:
      - postgresdb
  #postgres db definition the env vars should be put in a properties file and passed to it somehow
  postgresdb:
    image: postgres:10.4
    #the health check confirms that the db is ready to accept connections and not just the container
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - PGDATA=/var/lib/postgresql/data/db-files/
      - POSTGRES_USER=user
      - POSTGRES_HOST=host.docker.internal
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=customerdirectory
    #   Maps port 54320 (localhost) to port 5432 on the container. You can change the ports to fix your needs.
    ports:
      - "54320:5432"
    volumes:
      - ./postgres_volume:/var/lib/postgresql/data
