version: '3'
services:
  
  #mongodb set up
  web:
    build: ./mongodb_service
    container_name: web_mongodb_service
    ports:
    - 4000:4000
    depends_on:
    - mongodb

  mongodb:
    image: mongo
    expose:
    - '27017'

  web_postgres:
    build: ./postgres_service
    container_name: web_postgresdb_service
    ports:
      - "3000:3000"
    depends_on:
    - postgresdb
  
  #postgres db definition the env vars should be put in a properties file and passed to it somehow
  postgresdb:
    image: postgres
    #the health check confirms that the db is ready to accept connections and not just the container
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - PGUSER=user
      - PGPASSWORD=1234
      - PGPORT=5432
      - PGDATABASE=customerdirectory
#   Maps port 54320 (localhost) to port 5432 on the container. You can change the ports to fix your needs.
    ports:
      - "54320:5432"