apiVersion: v1
kind: Namespace
metadata:
   name: postgres-service-ns
   namespace: postgres-service-ns
---
apiVersion: v1
kind: Namespace
metadata:
   name: mongo-service-ns
   namespace: mongo-service-ns
---
